### ISSUE TITLE
XPDY0050 when running generate-tests-utils.xspec for XQuery

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#82]
Execute `test/generate-tests-utils.xspec` for XQuery (`-q` option). It terminates:

```winbatch
P:\xspec\test>..\bin\xspec.bat -q generate-tests-utils.xspec
Saxon script not found, invoking JVM directly instead.

Creating Test Stylesheet...

Running Tests...
Source document ignored - query does not access the context item
Error on line 256 column 211 of generate-tests-utils.xq:
  XPDY0050: The root of the tree containing the context item is not a document node
Query failed with dynamic error: The root of the tree containing the context item is not a document node

*** Error running the test suite
```

Tested on the latest master.

Looks like the error didn't happen until 86e9bbf676d027e14234338224977dc75b65d6b1

**Comment by cirulls** [comment]
@AirQuick : Is this now fixed by the merge in #83 (commit https://github.com/xspec/xspec/commit/120b3316aef2c1106287dc7c5270f3ed49062c68)? When I run it with the shell script, I now get all the XQuery tests passing:
```bash
bin/xspec.sh -q test/generate-x-utils.xspec                 
 
Saxon script not found, invoking JVM directly instead.

Creating Test Stylesheet...

Running Tests...
Source document ignored - query does not access the context item

Formatting Report...
passed: 8 / pending: 0 / failed: 0 / total: 8
Report available at test/xspec/generate-x-utils-result.html
Done.
```

**Comment by AirQuick** [comment]
Not fixed actually. But #83 has isolated the issue. Now we can run `generate-x-utils.xspec` on XQuery and we have an explicit [comment](https://github.com/xspec/xspec/blob/120b3316aef2c1106287dc7c5270f3ed49062c68/test/generate-tests-utils.xspec#L11) for the current limitation. So I think we can close this issue for now.

**Comment by cirulls** [comment]
Thanks for checking. I'll close this ticket for now, we will address the ```TODO``` comments for XQuery at some point in the future.
