### ISSUE TITLE
Code Coverage doesn't work on Saxon 10

### ISSUE THREAD

**Issue by AirQuick** [xspec/xspec#852]
http://www.saxonica.com/documentation/index.html#!changes/spi/9.9.1-10.0
> The mechanism supporting execution tracing (including the -T and -TP options on the command line) has been substantially revamped

**Comment by AirQuick** [comment]
Blocked by https://saxonica.plan.io/issues/4970

**Comment by jhellingman** [comment]
It looks like both blocking issues are now resolved on the Saxonica side.

**Comment by AirQuick** [comment]
Unfortunately I found the blocking issues not completely fixed. (Actually, 12.3 look worse than 10.7.)

**Comment by AirQuick** [comment]
Re-raised the issue: https://saxonica.plan.io/issues/6223

I already have a working code for Saxon 10+. Will submit a pull request once the Saxon bug is fixed.
